#!/bin/bash

# Define what WM/DE to execute
export SESSION="dwm"

# Executed by startx (run your window manager from here)
get_session(){
	case "$SESSION" in
		dwm) dwm ;;
		leftwm) leftwm ;;
	esac
}

# Configure keyboard repeat rate
if type xset > /dev/null 2>&1; then
	xset r rate 200 70 > /dev/null 2>&1
fi

if [[ "$SESSION" == "dwm" ]]; then
	# Configure wallpaper
	if type feh > /dev/null 2>&1 && [[ -d "$HOME/.local/share/wallpapers" ]]; then
		feh --bg-fill --no-fehbg --randomize "$HOME"/.local/share/wallpapers/* &
	else
		feh --bg-fill --no-fehbg /opt/dwm/backgroung.jpg &
	fi

	# Launch Simple X Hotkey Daemon
	if type sxhkd > /dev/null 2>&1; then
		sxhkd &
	fi

	# Launch Dunst if installed (notification)
	if type dunst > /dev/null 2>&1; then
		dunst &
	fi

	# Launch Unclutter (hide mouse cursor)
	if type unclutter > /dev/null 2>&1; then
		unclutter &
	fi

	# Launch Flameshot if installed
	if type flameshot > /dev/null 2>&1; then
		flameshot &
	fi

	# Launch 'dwmbar' script if running DWM
	if [[ "$SESSION" == "dwm" ]]; then
		dwmbar &
	fi

	# Display volume icon in systray
	if type volumeicon > /dev/null 2>&1; then
		volumeicon &
	fi

	# Turn on Numlock
	if type numlockx > /dev/null 2>&1; then
		numlockx on &
	fi

	# Launch a session manager
	if type lxpolkit > /dev/null 2>&1; then
		lxpolkit &
	fi

	# Launch a session manager
	if type lxsession > /dev/null 2>&1; then
		lxsession &
	fi

	# Launch compositer for fancy graphical effects
	if type picom > /dev/null 2>&1; then
		picom -CGb &
	fi
fi

# Launch the chosen GUI environment (must be last)
get_session "$1"
